import Head from "next/head";
import Image from 'next/image';

export default function Home() {

  return (
      <>
          <Head>
              <title>Remindme</title>
              <meta name="description" content="Generated by create next app" />
              <meta name="viewport" content="width=device-width, initial-scale=1" />
              <link rel="icon" href="/favicon.ico" />
          </Head>
          <div className="grid grid-cols-1 h-screen lg:grid-cols-2">
              <div className="flex bg-[#3a596b]">
                  <div className="flex flex-col bg-[#224559] pt-[50px] pl-[10px] pr-[10px] pb-[50px] clip-path-polygon-[_0_0,_100%_10%,_100%_90%,_0_76%]
              lg:clip-path-polygon-[_0_0,_100%_0,_100%_35%,_0_100%] lg:pt-[100px]
              lg:pl-[50px] lg:pr-[50px]
               ">
                      <p className=" lg:text-2xl text-[#fff] mb-[20px] text-lg ">RemindMe is a task management web app developed by Olive Inc. The platforms that allows users to create lists of reminders for medications and set notifications for themselves.</p>

                  </div>
              </div>

              <div className="lg:pt-[80px]">
                  <Image src='/undraw_mobile.png' alt='undraw'  width={1000} height={1000} quality={100}/>
              </div>
          </div>
      </>

  )
}
